### PR TITLE
About the new param called "placeHolder"

### PR DESCRIPTION
**Pull request by dharmann**
I wish to propose to use a configurable text to mimic MacOS behavior that show "Finder" when no other text is available.
In case an user doesn't want to show the current activity name nor has an active window, then a placeholder can be configured to appears.

### CODE REVIEW

**Comment by psifidotos** [comment]
show me  a screenshot please from settings window

**Comment by dharmann** [comment]
> show me a screenshot please from settings window

Screenshot_20191229_115244

**Comment by dharmann** [comment]
Actually I want to add better behavior in the settings window, enabling the placeholder only if the option "Hide activity information" is selected

**Comment by psifidotos** [comment]
> Actually I want to add better behavior in the settings window, enabling the placeholder only if the option "Hide activity information" is selected

I think I am starting to believe that I am going to accept it in the end...

1. Please move the Placeholder settings option under the Hide Activity Information and make it to be enabled only when the ActivityInformationOption is enabled

2. Why did you name it Placeholder? Is it a term used elsewhere also ?

**Comment by dharmann** [comment]
Ok, I've done what you asked.
I've chosen "placeHolder" as name, because it's only a label needed to fill the space and replicate a MacOS behavior. Do you think there is a better name?

**Comment by dharmann** [comment]
> This needs to be moved at the previous GridLayout exactly under columns:2

Maybe I don't understand...

**Comment by dharmann** [comment]
> This needs to be moved at the previous GridLayout exactly under columns:2

DONE!

**Comment by psifidotos** [comment]
Ok dont worry I will merge as it is now and I will make the corrections... You can see my upcoming commit to see what I referring to.

**Comment by dharmann** [comment]
> Ok dont worry I will merge as it is now and I will make the corrections... You can see my upcoming commit to see what I referring to.
Sorry @psifidotos, I've understand a little bit later and suddendly removed my wrong comment.
Anyway, I've applied the modifcation as you suggested

**Comment by psifidotos** [comment]
@dharmann  it have uploaded all required changes... ;)

**Comment by psifidotos** [comment]
@dharmann dont worry, I have uploaded all required changed... :)

**Pull request merged**
