### PR TITLE
Add the Fixed mode option

### PR DESCRIPTION
**Pull request by trmdi**
#87

### CODE REVIEW

**Comment by psifidotos** [comment]
looks ok,is it ready?

**Comment by psifidotos** [comment]
oh now i noticed it.. I think it is checkboxes in use.. After merge I might change it to radiobuttons  and see how this would go.

**Comment by psifidotos** [comment]
@trmdi this commit motivated me and I will provide 4 different length policies.

one of them will be fixed

**Comment by th3hamm0r** [comment]
Unfortunately the fixed type does not work for me, no matter what size I configure, it does not update the title widget. It seems that it just works like the maximum-size-type.

I've updated the plasmoid, also tried re-adding it, nothing helps.

**Comment by th3hamm0r** [comment]
Sry, after a restart it seems to work.

**Pull request closed without merging**
