### PR TITLE
Added a CMakeLists.txt and rearranged the directory structure

### PR DESCRIPTION
**Pull request by Petross404**
And it works!

### CODE REVIEW

**Comment by trmdi** [comment]
I think it could be more minimal.
For example, see my CMakeLists.txt file: https://build.opensuse.org/package/view_file/home:trmdi/applet-window-title/CMakeLists.txt?expand=1

**Comment by Petross404** [comment]
Well, I got many errors about unknown command `plasma_install_package`. I don't know why yours work without KDE* modules.

**Comment by trmdi** [comment]
Try this similar ebuild: https://gitweb.gentoo.org/repo/gentoo.git/tree/kde-misc/plasma-applet-network-monitor/plasma-applet-network-monitor-1.7.3.ebuild

**Comment by psifidotos** [comment]
this PR breaks current structure so I can not accept it

**Comment by Petross404** [comment]
> Try this similar ebuild: https://gitweb.gentoo.org/repo/gentoo.git/tree/kde-misc/plasma-applet-network-monitor/plasma-applet-network-monitor-1.7.3.ebuild

Yes this ebuild has a cmakelist.txt to work with.

> this PR breaks current structure so I can not accept it

One could argue that it fixes it so it can be more easily packaged :p Anyway, thanks!

**Comment by trmdi** [comment]
@Petross404

You can add it to your gentoo repo, like what I did with my opensuse repo. No problem.

**Comment by Petross404** [comment]
> @Petross404
> 
> You can add it to your gentoo repo, like what I did with my opensuse repo. No problem.

Yes, there is no other way (that I know at least) to be packaged.

**Comment by trmdi** [comment]
> > @Petross404
> > You can add it to your gentoo repo, like what I did with my opensuse repo. No problem.
> 
> Yes, there is no other way (that I know at least) to be packaged.

Another way, just copy all files to the plasmoid directory. Like this: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=plasma5-applets-window-title-git

**Pull request closed without merging**
